### ISSUE TITLE
SupersetApiError: Forbidden

### ISSUE THREAD

**Issue by pomegranited** [eduNEXT/platform-plugin-superset#5]
Hi @Ian2012 :)

I'm trying to install this plugin on my tutor dev stack, but the XBlock is throwing this error on render.
(It also logs me out of Superset whenever I refresh the XBlock page in the LMS or Studio, but that's a minor annoyance.)

Can you see what I'm doing wrong?

![image](https://github.com/eduNEXT/platform-plugin-superset/assets/7556571/8229c407-d7a7-4435-8056-1b06e250b740)

Superset logs:

```
tutor_dev-superset-1  | 172.27.0.12 - - [21/Feb/2024:02:44:58 +0000] "POST /api/v1/security/login HTTP/1.1" 200 413 "-" "python-requests/2.28.2"
tutor_dev-superset-1  | 172.27.0.12 - - [21/Feb/2024:02:44:58 +0000] "GET /api/v1/security/csrf_token/ HTTP/1.1" 200 105 "http://superset:8088/api/v1" "python-requests/2.28.2"
tutor_dev-superset-1  | 172.27.0.12 - - [21/Feb/2024:02:44:58 +0000] "POST /api/v1/security/guest_token/ HTTP/1.1" 200 390 "http://superset:8088/api/v1" "python-requests/2.28.2"
tutor_dev-superset-1  | 2024-02-21 02:44:59,207:WARNING:root:Class 'werkzeug.local.LocalProxy' is not mapped
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:44:59 +0000] "GET /embedded/87ccd334-127a-4078-a6b5-64b69a18c90d?uiConfig=11&expand_filters=false HTTP/1.1" 200 50914 "http://local.overhang.io:8000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:44:59 +0000] "GET /api/v1/me/roles/ HTTP/1.1" 200 150 "http://superset.local.overhang.io:8088/embedded/87ccd334-127a-4078-a6b5-64b69a18c90d?uiConfig=11&expand_filters=false" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:45:00 +0000] "GET /api/v1/dashboard/28 HTTP/1.1" 403 24 "http://superset.local.overhang.io:8088/embedded/87ccd334-127a-4078-a6b5-64b69a18c90d?uiConfig=11&expand_filters=false" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:45:00 +0000] "GET /api/v1/dashboard/28/charts HTTP/1.1" 403 24 "http://superset.local.overhang.io:8088/embedded/87ccd334-127a-4078-a6b5-64b69a18c90d?uiConfig=11&expand_filters=false" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:45:00 +0000] "GET /api/v1/dashboard/28/datasets HTTP/1.1" 403 24 "http://superset.local.overhang.io:8088/embedded/87ccd334-127a-4078-a6b5-64b69a18c90d?uiConfig=11&expand_filters=false" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
tutor_dev-superset-1  | 172.27.0.1 - - [21/Feb/2024:02:45:00 +0000] "GET /static/assets/f8a10326828318d2245e.woff2 HTTP/1.1" 200 0 "http://superset.local.overhang.io:8088/static/assets/theme.210d3997a2ed5cd99e9f.entry.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0"
```

Superset XBlock config:

* Superset url: Had to leave this blank.
  I tried all of these, but the XBlock shows errors: 
   `http://supserset:8088/`: authentication in the backend succeeds, but iframe fails to load "cannot connect to server"
   `http://localhost:8088/`: "Connection refused"
   `http://superset.local.overhang.io:8088/`: "Connection refused"
   
* Superset username and Superset password: tried leaving these blank, and tried both of the tutor-generated admin users:
   `SUPERSET_LMS_USERNAME` / `SUPERSET_LMS_PASSWORD` 
   `SUPERSET_ADMIN_USERNAME` / `SUPERSET_ADMIN_PASSWORD`
   
   Can't use any SSO user credentials; they can't authenticate to Superset API.
   
*  Dashboard UUID : chose the dashboard to share, enabled it for embedding, and pasted in the UUID.

   Tried embedding with and without any "allowed domains", no difference to the error.

* Filters: tried leaving this blank, or using `org='edX'`, no difference to the error.

**Comment by Ian2012** [comment]
This is because you need to grant the following permissions to the public role:

![image](https://github.com/eduNEXT/platform-plugin-superset/assets/33465240/ce5d1a67-fabc-4c48-8e3d-b41b86c8f69d)

For the closing session, that's how guest tokens work currently. Not sure if we can do something about it

**Comment by pomegranited** [comment]
@Ian2012 Yes! Your https://github.com/openedx/tutor-contrib-aspects/pull/612 fixed my permissions issue, thank you!
